AddEventHandler("playerSpawned", function(spawn)
TriggerEvent("chatMessage", "", { 0, 0, 0 }, "Enter here")
TriggerEvent("chatMessage", "", { 0, 0, 0 }, "Enter here")
TriggerEvent("chatMessage", "", { 0, 0, 0 }, "Enter here")
TriggerEvent("chatMessage", "", { 0, 0, 0 }, "Enter here")
end)
